### ISSUE TITLE
간혹 주가 데이터에서 손실되는 부분이 생깁니다

### ISSUE THREAD

**Issue by melemo2** [financedata-org/FinanceDataReader#101]
3년이상 긴 데이터를 가져올때 간혹 주가 데이터에서 손실되는 부분이 생깁니다
다시 그부분만 날짜 지정해서 load하면 정상적으로 불러와지구요

**Comment by FinanceData** [comment]
사용하신 코드와 어느 부분이 누락되었는지 알려주시면 더 도움이 되겠습니다.
