### ISSUE TITLE
다우존스(DJI) 종가 값이 investing.com 결과와 맞지 않는 이유는 뭘까요 ? 

### ISSUE THREAD

**Issue by devyoon91** [financedata-org/FinanceDataReader#105]
DJI, IXIC, US500 지수 데이터를 매일 확인하고 있는데요 

요 근래 다우존스(DJI) 의 종가가 investing과 계속 달라서 문의 드립니다

### 다우존스 (DJI), 2021-10-12 
- https://kr.investing.com/indices/us-30
![image](https://user-images.githubusercontent.com/59568331/137047784-6f4615c8-0a2e-4f7b-afa6-2350c6fa2daa.png)

### FinanceDataReader 결과
- `dji = fdr.DataReader('DJI', '2021-10-12', '2021-10-12')` 실행 결과
![image](https://user-images.githubusercontent.com/59568331/137047943-2445cd55-6b64-44d3-87ee-fb85cfd50dbf.png)

**Comment by kimdesok** [comment]
?

**Comment by devyoon91** [comment]
?
