### ISSUE TITLE
심볼 중복

### ISSUE THREAD

**Issue by mk-kang1** [financedata-org/FinanceDataReader#112]
![image](https://user-images.githubusercontent.com/71447571/146745699-27fdc4df-dd1c-42e6-8aa8-7d988e060f86.png)

FinanceDataReader/docs/tickers.rst에서 보면 KONEX심볼이 중복되서 나오는 것을 볼 수 있습니다.

중복을 제거해서 변경해도 될까요?

**Comment by FinanceData** [comment]
수정하였습니다
