### ISSUE TITLE
항셍지수 값 오류

### ISSUE THREAD

**Issue by littlehongkong** [financedata-org/FinanceDataReader#129]
HSI라는 종목코드가 있어서 그런지 이상한값을 보내주네요.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/11766241/165080064-92472496-46a5-408a-9270-e62db487141c.png">

**Comment by FinanceData** [comment]
Release 0.9.50 에서 FIX 하였습니다. 
상세한 내용을 아래 Release Note 참고하시기 바랍니다.

https://github.com/financedata-org/FinanceDataReader/wiki/Release-Note-0.9.50
