### ISSUE TITLE
df.append 경고메시지

### ISSUE THREAD

**Issue by IAMNOTAHUMANBEING** [financedata-org/FinanceDataReader#137]
https://github.com/FinanceData/FinanceDataReader/issues/120
윗 글에서  수정반영하셨다고 하셨는데 경고메세지가 뜨네요

![image](https://user-images.githubusercontent.com/60809568/179385850-aec5941c-bfa6-4262-8a4f-90b3a2069172.png)

![image](https://user-images.githubusercontent.com/60809568/179385823-53b2197e-9351-406d-a14c-7b8721d4e36c.png)

![image](https://user-images.githubusercontent.com/60809568/179385813-9898daaa-fe5b-4313-b5b3-2c474b456371.png)

현재 버전과 에러 메시지, 라이브러리 코드를 첨부하였습니다.

**Comment by FinanceData** [comment]
Release-Note-0.9.40 에서 FIX 하였습니다
