### ISSUE TITLE
fdr.StockListing("ETF/US")가 다시 안 되나요?

### ISSUE THREAD

**Issue by WonSeokChoi-Unicorn** [financedata-org/FinanceDataReader#150]
0.9.34 사용 중인데

  File "C:\Python38\lib\site-packages\FinanceDataReader\data.py", line 76, in StockListing
    return InvestingEtfListing(country).read()        
  File "C:\Python38\lib\site-packages\FinanceDataReader\investing\listing.py", line 32, in read
    data_id = tds[1].span['data-id']
  File "C:\Python38\lib\site-packages\bs4\element.py", line 1486, in __getitem__
    return self.attrs[key]
KeyError: 'data-id'

이런 에러가 발생합니다.

이건 새로운 에러라서 수정이 필요한 것일까요?

8월 5일까지는 정상 실행 되었는데 8월 6일부터 에러가 발생하고 있습니다.

**Comment by WonSeokChoi-Unicorn** [comment]
바쁘신 것 같네요.

원인인지 몰라도 
이전)
        values = []
        trs = table.tbody.find_all('tr')
        for tr in trs:
            tds = tr.find_all('td')
            data_id = tds[1].span['data-id']
            sym = tds[2].text
            name = tds[1].a.text
            values.append([sym, name])

        df = pd.DataFrame(values, columns=['Symbol', 'Name'])  
        return df

변경
        values = []
        trs = table.tbody.find_all('tr')
        for tr in trs:
            tds = tr.find_all('td')
            # data_id = tds[1].span['data-id']
            sym = tds[2].text
            name = tds[1].text
            values.append([sym, name])

        df = pd.DataFrame(values, columns=['Symbol', 'Name'])  
        return df


data_id 부분은 의미 없는 것 같아서 주석 처리했고
name 은 웹사이트가 변경되어서 a를 삭제했습니다.

다음 업데이트 때 반영해주시면 되겠습니다.

**Comment by FinanceData** [comment]
2022-09-23 [Release Note 0.9.40](https://github.com/financedata-org/FinanceDataReader/wiki/Release-Note-0.9.40) 에서 FIX 하였습니다
