### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0) 이 뜹니다.

### ISSUE THREAD

**Issue by MLOpsEngineer** [financedata-org/FinanceDataReader#152]
안녕하세요! 만들어주신 패키지 너무 잘 쓰고 있습니다. 감사합니다 :)
저는 아래와 같은 금융상품 데이터를 수집해서 쓰고 있는데 갑자기 JSONDecodeError: Expecting value: line 1 column 1 (char 0) 뜨면서 수집이 되지 않네요ㅠㅠ 미국시장 데이터 뿐만 아니라 국내와 가상화폐까지 전부 되지 않는게 조금 이상해서요. 패키지 내용 확인하니까 각 자산마다 수집하는 사이트가 다른 걸로 확인이 되었는데 혹시 어떤 이유때문에 작동하지 않는걸까요.
시간 괜찮으실 때 한번 확인 부탁드리겠습니다! 
감사합니다 :)
 [
    ‘BTC/USD’,
    ‘KS11’, ‘DJI’, ‘US500’, ‘SSEC’, ‘JP225’, ‘UK100’, ‘STOXX50’, ‘DE30’, ‘FCHI’,
    ‘GC’, ‘NG’, ‘HG’, ‘CL’,
    ‘US1MT=X’, ‘US6MT=X’, ‘US1YT=X’, ‘US5YT=X’, ‘US10YT=X’, ‘US30YT=X’,
    ‘USD/KRW’, ‘USD/RUB’, ‘USD/EUR’,
    ‘VIX’
  ]

**Comment by bankplus** [comment]
네... 코스닥, 코스피 지수들도 다 동일한 에러가 뜹니다.

**Comment by FinanceData** [comment]
데이터를 가져오는 investing.com 자체에 상당한 변화가 생겼습니다 (9/14일 인 듯 합니다)
언급하신 데이터는 모두 investing.com 에서 가져옵니다.

investing.com 자체 내부 api를 사용하는 형식으로 바뀌고, api에 대한 인증을 사용하는 형식으로 변경되었네요.

대응하는데 몇 일 정도 시간이 소요 될 것으로 보입니다.

현재 investing.com 변화에 대응하는 방향과 investing.com 을 대체하여 다른 데이터소스로 변경하는 두가지 방안을 검토하고 있습니다.  investing.com 이 크롤링을 막기위한 조치(예를 들어 주기적 조회에 IP-BAN) 추가 하고 있어서 중장기 적으로 계속 사용하기 어렵다고 판단하고 있습니다.

**Comment by JoshuaChung93** [comment]
저도 동일한 오류 떴었는데 인베스팅닷컴 업데이트 때문이었군요..

**Comment by rookie777-dotcom** [comment]
너무나 편리하게 잘 사용해왔는데 이렇게 되니 참 소중했구나 싶습니다. 다시 이용할 수 있기를 바래봅니다. 감사드립니다.

**Comment by KyleL22** [comment]
미주만 안되는게 이가 있었군요

**Comment by yunkujeon** [comment]
코드 수정되면 공지 부탁드립니다~
항상 감사드립니다.

**Comment by verdantpond** [comment]
저도 오류가 있어서 이리저리 헤매다 여기까지 왔는데....결국 인베스팅의 문제였군요. 빨리 해결되길 응원합니다.

**Comment by FinanceData** [comment]
2022-09-23 [Release Note 0.9.40](https://github.com/financedata-org/FinanceDataReader/wiki/Release-Note-0.9.40) 에서 FIX 하였습니다
