### ISSUE TITLE
0.9.40. 인베스팅 api read timeout 처리시 문제

### ISSUE THREAD

**Issue by tyolee** [financedata-org/FinanceDataReader#154]
read timeout 발생시 time.sleep(2) 하고 재시도 하게끔 되어있는데 아래와 같이 에러납니다.

venv/lib/python3.10/site-packages/FinanceDataReader/investing/data.py", line 67, in read
    time.sleep(2)
NameError: name 'time' is not defined

import time이 필요하지 않을까 싶은데, 확인 부탁 드립니다.

그리고 다량 요청에 대해 블록 당하는 문제 해결되었다고 해서 호출시 sleep 걸어주는 부분을 풀었는데,

read timeout 나는게 또 블럭 당하는건 아닌가 싶네요...ㅠ

**Comment by FinanceData** [comment]
NameError: name 'time' is not defined 부분 수정 반영 하였습니다 (Release 0.9.42)
에러 부분은 말씀 대로 'import time'이 누락된 것입니다.

데이터를 1년치씩 나누어 가져오기 때문에 속도가 다소 느려졌지만, 현재까지 블럭당하는 사례는 없었습니다~
의견 감사합니다. 😸
