### ISSUE TITLE
financedata 지금 작동이되나요?

### ISSUE THREAD

**Issue by ildgme** [financedata-org/FinanceDataReader#159]
어떤종목도 받아지지가 않네요.
오류만 나오면서 아무것도 안됩니다. 
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE html>

일시적인 현상인가요?

**Comment by FinanceData** [comment]
에러메지시는 이전 버전에서 발생한 것으로 보입니다. 업데이트를 해보셨는지요?

```bash
!pip install --upgrade finance-datareader
```

그래도 계속 문제가 있다면 코드를 알려주시면 감사합니다 (심볼과 기간 확인을 위해서입니다)

**Comment by FinanceData** [comment]
#166 이슈에서 트래킹하겠습니다
