### ISSUE TITLE
종목 리스트 불러 올 때 종목과 펀드를 분리하는 방법은?

### ISSUE THREAD

**Issue by cahn70** [financedata-org/FinanceDataReader#86]
안녕하세요? 
이제까지 네이버에서 데이터를 가져 왔었는데, 수정종가 지원이 안되어 고민하던 차에, 
FinanceDataReader를 알게 되어 활용해 보려고 이런 저런 테스트를 해보고 있습니다.
일단은 수정종가 지원이 되서 너무 기쁘네요... ^^

문의드리고 싶은 내용은,
StockListing('KRX')로 종목 리스트를 가져오면, 아래와 같이 단일 종목 외에 다양한 펀드 등까지 다 같이 가져오는 것 같더라구요...
현재 상장된 종목이 2400여개인데 7297개가 검색이 되고.... 
내용도 풋, 콜 등 다양한 종목이 같이 들어가 있네요...

df_krx = fdr.StockListing('KRX')
print(len(df_krx))
7297

StockListing('KOSPI')나 StockListing('KOSDAQ'도 확인해 보니 마찬가지이구요...

혹시 단일 종목과 펀드나 그 외의 종목을 분리해서 불러올 수 있는 옵션이 있을까요?

다시 한번 좋은 라이브러리 만들어 주셔서 감사를 드립니다.^^

**Comment by FinanceData** [comment]
개별주식 종목은 Sector 와 Industry 가 부여되어 있습니다.  
따라서 다음과 같이 구분이 가능할 것 같습니다.

```python
df[df['Sector'].isnull()] # 개별주식외 펀드, ETF 등
df[~df['Sector'].isnull()] # 개별주식
```

**Comment by FinanceData** [comment]
상장회사와 상장종목 구분을 구분하여 listing 하도록 하였습니다.
상세한 내용을 아래 Release Note 참고하시기 바랍니다.

https://github.com/financedata-org/FinanceDataReader/wiki/Release-Note-0.9.50
