### ISSUE TITLE
해외종목의 경우 investing.com에 표시되는 것과 다릅니다.

### ISSUE THREAD

**Issue by 2p990i9hpral** [financedata-org/FinanceDataReader#92]
"금": "ZG",
"은": "ZI",
"구리": "HG",
"WTI": "T",
"옥수수": "ZC",

```
now_date = datetime.datetime.now()
    stock_data = fdr.DataReader(stock, now_date.strftime('%Y-%m-%d'), exchange=exchange)

  while stock_data.size == 0:
      now_date = (now_date - datetime.timedelta(days=1))
      stock_data = fdr.DataReader(stock, now_date.strftime('%Y-%m-%d'), exchange=exchange)
```

현재가를 가져오기 위해 당일 조회하고 없을 경우 전일 조회하는 방식으로 코딩하였는데
investing.com에 표시되는 것과 다르네요..
해결법이 있다면 공유 부탁드리겠습니다.

감사합니다.

**Comment by FinanceData** [comment]
"표시되는 것이 다르다"라고 말씀하셨는데 어떻게 다른지 말씀 주시면 더 도움이 될 것 같습니다.

**Comment by FinanceData** [comment]
가장 최신 가격을 가져오는 것이 목적이시라면 다음과 같이 간단하게 해결 가능해 보입니다. (현재는 거래량이 없는 휴일은 제외하고 있습니다)

```python
import FinanceDataReader as fdr

df = fdr.DataReader('ZG')
df.iloc[-1]['Close']
```

**Comment by 2p990i9hpral** [comment]
7월 13일 오후 2시 기준 
```
stock_df = fdr.DataReader('ZC')

    print(stock_df.iloc[-1]['Close'])
```
위 소스로 가져온 가격은 669.25 입니다.

https://kr.investing.com/commodities/us-corn
반면 위 종목에 해당하는 인베스팅 웹 사이트에서 확인하였을 때는 528.90 로 표시됩니다.

이런 차이가 발생하는 이유가 무엇인가요?

**Comment by FinanceData** [comment]
현재는 investing 에서 데이터를 가져오지 않고 있어서 이슈를 Close 합니다
